let TextZone = document.getElementById("TZ");
let label_1 = document.getElementById("label1");
let label_2 = document.getElementById("label2");
let label_3 = document.getElementById("label3");
let label_4 = document.getElementById("label4");
let ClearText =()=>{
    TextZone.value="";
    TextZone.style.color="Black";
    label_1.value=" ";
    label_2.value=" ";
    label_3.value="";
    label_4.value="";
};
let check =()=>{
    if (TextZone.value == "" || TextZone.value == "Almost before we knew it, we had left the ground..."){}
    else {
        let Text = TextZone.value;
        let newText1 = Text
            .replace(/A/g,"Ⓐ")
            .replace(/B/g,"Ⓑ")
            .replace(/C/g,"Ⓒ")
            .replace(/D/g,"Ⓓ")
            .replace(/E/g,"Ⓔ")
            .replace(/F/g,"Ⓕ")
            .replace(/G/g,"Ⓖ")
            .replace(/H/g,"Ⓗ")
            .replace(/I/g,"Ⓘ")
            .replace(/J/g,"Ⓙ")
            .replace(/K/g,"Ⓚ")
            .replace(/L/g,"Ⓛ")
            .replace(/M/g,"Ⓜ")
            .replace(/N/g,"Ⓝ")
            .replace(/O/g,"Ⓞ")
            .replace(/P/g,"Ⓟ")
            .replace(/Q/g,"Ⓠ")
            .replace(/R/g,"Ⓡ")
            .replace(/S/g,"Ⓢ")
            .replace(/T/g,"Ⓣ")
            .replace(/U/g,"Ⓤ")
            .replace(/V/g,"Ⓥ")
            .replace(/W/g,"Ⓦ")
            .replace(/X/g,"Ⓧ")
            .replace(/Y/g,"Ⓨ")
            .replace(/Z/g,"Ⓩ")

            .replace(/a/g,"ⓐ")
            .replace(/b/g,"ⓑ")
            .replace(/c/g,"ⓒ")
            .replace(/d/g,"ⓓ")
            .replace(/e/g,"ⓔ")
            .replace(/f/g,"ⓕ")
            .replace(/g/g,"ⓖ")
            .replace(/h/g,"ⓗ")
            .replace(/i/g,"ⓘ")
            .replace(/j/g,"ⓙ")
            .replace(/k/g,"ⓚ")
            .replace(/l/g,"ⓛ")
            .replace(/m/g,"ⓜ")
            .replace(/n/g,"ⓝ")
            .replace(/o/g,"ⓞ")
            .replace(/p/g,"ⓟ")
            .replace(/q/g,"ⓠ")
            .replace(/r/g,"ⓡ")
            .replace(/s/g,"ⓢ")
            .replace(/t/g,"ⓣ")
            .replace(/u/g,"ⓤ")
            .replace(/v/g,"ⓥ")
            .replace(/w/g,"ⓦ")
            .replace(/x/g,"ⓧ")
            .replace(/y/g,"ⓨ")
            .replace(/z/g,"ⓩ")

            .replace(/1/g,"①")
            .replace(/2/g,"②")
            .replace(/3/g,"③")
            .replace(/4/g,"④")
            .replace(/5/g,"⑤")
            .replace(/6/g,"⑥")
            .replace(/7/g,"⑦")
            .replace(/8/g,"⑧")
            .replace(/9/g,"⑨");


        let newText2 = Text
            .replace(/A/g,"𝓐")
            .replace(/B/g,"𝓑")
            .replace(/C/g,"𝓒")
            .replace(/D/g,"𝓓")
            .replace(/E/g,"𝓔")
            .replace(/F/g,"𝓕")
            .replace(/G/g,"𝓖")
            .replace(/H/g,"𝓗")
            .replace(/I/g,"𝓘")
            .replace(/J/g,"𝓙")
            .replace(/K/g,"𝓚")
            .replace(/L/g,"𝓛")
            .replace(/M/g,"𝓜")
            .replace(/N/g,"𝓝")
            .replace(/O/g,"𝓞")
            .replace(/P/g,"𝓟")
            .replace(/Q/g,"𝓠")
            .replace(/R/g,"𝓡")
            .replace(/S/g,"𝓢")
            .replace(/T/g,"𝓣")
            .replace(/U/g,"𝓤")
            .replace(/V/g,"𝓥")
            .replace(/W/g,"𝓦")
            .replace(/X/g,"𝓧")
            .replace(/Y/g,"𝓨")
            .replace(/Z/g,"𝓩")

            .replace(/a/g,"𝓪")
            .replace(/b/g,"𝓫")
            .replace(/c/g,"𝓬")
            .replace(/d/g,"𝓭")
            .replace(/e/g,"𝓮")
            .replace(/f/g,"𝓯")
            .replace(/g/g,"𝓰")
            .replace(/h/g,"𝓱")
            .replace(/i/g,"𝓲")
            .replace(/j/g,"𝓳")
            .replace(/k/g,"𝓴")
            .replace(/l/g,"𝓵")
            .replace(/m/g,"𝓶")
            .replace(/n/g,"𝓷")
            .replace(/o/g,"𝓸")
            .replace(/p/g,"𝓹")
            .replace(/q/g,"𝓺")
            .replace(/r/g,"𝓻")
            .replace(/s/g,"𝓼")
            .replace(/t/g,"𝓽")
            .replace(/u/g,"𝓾")
            .replace(/v/g,"𝓿")
            .replace(/w/g,"𝔀")
            .replace(/x/g,"𝔁")
            .replace(/y/g,"𝔂")
            .replace(/z/g,"𝔃")

            .replace(/0/g,"𝟘")
            .replace(/1/g,"𝟙")
            .replace(/2/g,"𝟚")
            .replace(/3/g,"𝟛")
            .replace(/4/g,"𝟜")
            .replace(/5/g,"𝟝")
            .replace(/6/g,"𝟞")
            .replace(/7/g,"𝟟")
            .replace(/8/g,"𝟠")
            .replace(/9/g,"𝟡");


        let newText3 = Text
            .replace(/A/g,"𝔸")
            .replace(/B/g,"𝔹")
            .replace(/C/g,"ℂ")
            .replace(/D/g,"𝔻")
            .replace(/E/g,"𝔼")
            .replace(/F/g,"𝔽")
            .replace(/G/g,"𝔾")
            .replace(/H/g,"ℍ")
            .replace(/I/g,"𝕀")
            .replace(/J/g,"𝕁")
            .replace(/K/g,"𝕂")
            .replace(/L/g,"𝕃")
            .replace(/M/g,"𝕄")
            .replace(/N/g,"ℕ")
            .replace(/O/g,"𝕆")
            .replace(/P/g,"ℙ")
            .replace(/Q/g,"ℚ")
            .replace(/R/g,"ℝ")
            .replace(/S/g,"𝕊")
            .replace(/T/g,"𝕋")
            .replace(/U/g,"𝕌")
            .replace(/V/g,"𝕍")
            .replace(/W/g,"𝕎")
            .replace(/X/g,"𝕏")
            .replace(/Y/g,"𝕐")
            .replace(/Z/g,"ℤ")

            .replace(/a/g,"𝕒")
            .replace(/b/g,"𝕓")
            .replace(/c/g,"𝕔")
            .replace(/d/g,"𝕕")
            .replace(/e/g,"𝕖")
            .replace(/f/g,"𝕗")
            .replace(/g/g,"𝕘")
            .replace(/h/g,"𝕙")
            .replace(/i/g,"𝕚")
            .replace(/j/g,"𝕛")
            .replace(/k/g,"𝕜")
            .replace(/l/g,"𝕝")
            .replace(/m/g,"𝕞")
            .replace(/n/g,"𝕟")
            .replace(/o/g,"𝕠")
            .replace(/p/g,"𝕡")
            .replace(/q/g,"𝕢")
            .replace(/r/g,"𝕣")
            .replace(/s/g,"𝕤")
            .replace(/t/g,"𝕥")
            .replace(/u/g,"𝕦")
            .replace(/v/g,"𝕧")
            .replace(/w/g,"𝕨")
            .replace(/x/g,"𝕩")
            .replace(/y/g,"𝕪")
            .replace(/z/g,"𝕫")

            .replace(/0/g,"𝟘")
            .replace(/1/g,"𝟙")
            .replace(/2/g,"𝟚")
            .replace(/3/g,"𝟛")
            .replace(/4/g,"𝟜")
            .replace(/5/g,"𝟝")
            .replace(/6/g,"𝟞")
            .replace(/7/g,"𝟟")
            .replace(/8/g,"𝟠")
            .replace(/9/g,"𝟡");




        let newText4 = Text
            .replace(/A/g,"ል")
            .replace(/B/g,"ጌ")
            .replace(/C/g,"ር")
            .replace(/D/g,"ዕ")
            .replace(/E/g,"ቿ")
            .replace(/F/g,"ቻ")
            .replace(/G/g,"ኗ")
            .replace(/H/g,"ዘ")
            .replace(/I/g,"ጎ")
            .replace(/J/g,"ጋ")
            .replace(/K/g,"ጕ")
            .replace(/L/g,"ረ")
            .replace(/M/g,"ጠ")
            .replace(/N/g,"ክ")
            .replace(/O/g,"ዐ")
            .replace(/P/g,"የ")
            .replace(/Q/g,"ዒ")
            .replace(/R/g,"ዪ")
            .replace(/S/g,"ነ")
            .replace(/T/g,"ፕ")
            .replace(/U/g,"ሁ")
            .replace(/V/g,"ሀ")
            .replace(/W/g,"ሠ")
            .replace(/X/g,"ሸ")
            .replace(/Y/g,"ሃ")
            .replace(/Z/g,"ጊ")

            .replace(/a/g,"ል")
            .replace(/b/g,"ጌ")
            .replace(/c/g,"ር")
            .replace(/d/g,"ዕ")
            .replace(/e/g,"ቿ")
            .replace(/f/g,"ቻ")
            .replace(/g/g,"ኗ")
            .replace(/h/g,"ዘ")
            .replace(/i/g,"ጎ")
            .replace(/j/g,"ጋ")
            .replace(/k/g,"ጕ")
            .replace(/l/g,"ረ")
            .replace(/m/g,"ጠ")
            .replace(/n/g,"ክ")
            .replace(/o/g,"ዐ")
            .replace(/p/g,"የ")
            .replace(/q/g,"ዒ")
            .replace(/r/g,"ዪ")
            .replace(/s/g,"ነ")
            .replace(/t/g,"ፕ")
            .replace(/u/g,"ሁ")
            .replace(/v/g,"ሀ")
            .replace(/w/g,"ሠ")
            .replace(/x/g,"ሸ")
            .replace(/y/g,"ሃ")
            .replace(/z/g,"ጊ")

            .replace(/0/g,"𝟘")
            .replace(/1/g,"𝟙")
            .replace(/2/g,"𝟚")
            .replace(/3/g,"𝟛")
            .replace(/4/g,"𝟜")
            .replace(/5/g,"𝟝")
            .replace(/6/g,"𝟞")
            .replace(/7/g,"𝟟")
            .replace(/8/g,"𝟠")
            .replace(/9/g,"𝟡");

        label_1.value=newText1;
        label_2.value=newText2;
        label_3.value=newText3;
        label_4.value=newText4;
    }
};
setInterval(check,1);
